### PR TITLE
Add support for running DQD behind a reverse proxy.

### PR DESCRIPTION
**Pull request by kirenotneb**
# Overview

Added a custom `index.html` to prevent errors from occurring when running the DQD Shiny app behind a reverse proxy.

## Discussion

The new file eliminates the separate call to the `loadResults()` method when the location.port is over a general web port. This causes the `loadResults()` method to be executed twice which throws a DataTable error and prevents the table rows from expanding or collapsing. This will likely need to be updated with each new version of the DQD to ensure compatibility.

### CODE REVIEW

**Comment by heathharrelson** [comment]
@kirenotneb I'm adding my comments from Jira here as well. The code in your PR looks correct to me. My only concern is that, as you noted above, the template will need to be checked carefully each time that DQD is released upstream. This may not be a problem if DQD releases are infrequent, or if you plan on submitting an issue about the behavior with the upstream repository.

**Comment by heathharrelson** [comment]
One other thought — it might be good to add an HTML comment explaining why the `<script>` block is commented out, perhaps with a link to this PR.

**Comment by kirenotneb** [comment]
> One other thought — it might be good to add an HTML comment explaining why the `<script>` block is commented out, perhaps with a link to this PR.

Good call out. I'll make that change.

**Comment by kirenotneb** [comment]
The error produced is because the script detects the site is running from a webserver and thus attempts to run the `loadResults()` a second time. See [this DataTables article](https://datatables.net/manual/tech-notes/3) for additional details.

**Pull request merged**
